# grid size
grid-rows: 2
grid-columns: 5
grid-gap: 10

# styles
classes {

    #
    blank: {
        label: ""
        height: 50
        style: {
            fill: transparent
            stroke: transparent
        }
    }

}

# rooms

0,0: Elevator.c \#3
0,1.class: blank
0,2: Attic.c
0,3.class: blank
0,4.class: blank

1,0.class: blank
1,1.class: blank
1,2.class: blank
1,3.class: blank
1,4.class: blank

2,0: Elevator.c \#2
2,1.class: blank
2,2.class: blank
2,3.class: blank
2,4: Church.c

3,0.class: blank
3,1.class: blank
3,2: Quest_Room.c
3,3.class: blank
3,4.class: blank

4,0.class: blank
4,1.class: blank
4,2.class: blank
4,3.class: blank
4,4.class: blank

5,0: Elevator.c \#1
5,1.class: blank
5,2: Wiz_Hall.c
5,3.class: blank
5,4.class: blank

6,0.class: blank
6,1.class: blank
6,2.class: blank
6,3.class: blank
6,4: Green.c


# connections

# Elevator3
0,0 <-> 0,2
0,0 <-> 2,0

# Elevator 2
2,0 <-> 2,4
2,0 <-> 5,0

# Elevator 1
5,0 <-> 5,2

#Wizhall
5,2 <-> 3,2

#Church
2,4 <-> 6,4

